services:
  profiler:
    build:
      context: .
    container_name: profiler
    environment:
      VK_URL: ${VK_URL:-http://voight-kampff:8080}
      MQTT_HOST: ${MQTT_HOST:-mosquitto-broker}
      MQTT_PORT: ${MQTT_PORT:-1883}
      MQTT_SERVICE_USERNAME: ${MQTT_SERVICE_USERNAME}
      MQTT_SERVICE_API_KEY: ${MQTT_SERVICE_API_KEY}
    networks:
      - ansible
    restart: unless-stopped

networks:
  ansible:
    external: true
